// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface CMDReceiver extends Ice.Object,
                                     _CMDReceiverOperations, _CMDReceiverOperationsNC
{
    public static final String ice_staticId = "::Chat::CMDReceiver";

    public static final long serialVersionUID = 2142456112L;
}
