// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public final class CMDReceiverHolder extends Ice.ObjectHolderBase<CMDReceiver>
{
    public
    CMDReceiverHolder()
    {
    }

    public
    CMDReceiverHolder(CMDReceiver value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof CMDReceiver)
        {
            value = (CMDReceiver)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _CMDReceiverDisp.ice_staticId();
    }
}
