// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public final class MessageReceiverPrxHelper extends Ice.ObjectPrxHelperBase implements MessageReceiverPrx
{
    private static final String __onMessage_name = "onMessage";

    public void onMessage(String sender, String msg)
    {
        onMessage(sender, msg, null, false);
    }

    public void onMessage(String sender, String msg, java.util.Map<String, String> __ctx)
    {
        onMessage(sender, msg, __ctx, true);
    }

    private void onMessage(String sender, String msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_onMessage(begin_onMessage(sender, msg, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_onMessage(String sender, String msg)
    {
        return begin_onMessage(sender, msg, null, false, false, null);
    }

    public Ice.AsyncResult begin_onMessage(String sender, String msg, java.util.Map<String, String> __ctx)
    {
        return begin_onMessage(sender, msg, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_onMessage(String sender, String msg, Ice.Callback __cb)
    {
        return begin_onMessage(sender, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_onMessage(String sender, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_onMessage(sender, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_onMessage(String sender, String msg, Callback_MessageReceiver_onMessage __cb)
    {
        return begin_onMessage(sender, msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_onMessage(String sender, String msg, java.util.Map<String, String> __ctx, Callback_MessageReceiver_onMessage __cb)
    {
        return begin_onMessage(sender, msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_onMessage(String sender, 
                                           String msg, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_onMessage(sender, msg, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_onMessage(String sender, 
                                           String msg, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_onMessage(sender, msg, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_onMessage(String sender, 
                                           String msg, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_onMessage(sender, msg, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_onMessage(String sender, 
                                           String msg, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_onMessage(sender, msg, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_onMessage(String sender, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_onMessage(sender, 
                               msg, 
                               __ctx, 
                               __explicitCtx, 
                               __synchronous, 
                               new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_onMessage(String sender, 
                                            String msg, 
                                            java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__onMessage_name, __cb);
        try
        {
            __result.prepare(__onMessage_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(sender);
            __os.writeString(msg);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_onMessage(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __onMessage_name);
    }

    public static MessageReceiverPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), MessageReceiverPrx.class, MessageReceiverPrxHelper.class);
    }

    public static MessageReceiverPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), MessageReceiverPrx.class, MessageReceiverPrxHelper.class);
    }

    public static MessageReceiverPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), MessageReceiverPrx.class, MessageReceiverPrxHelper.class);
    }

    public static MessageReceiverPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), MessageReceiverPrx.class, MessageReceiverPrxHelper.class);
    }

    public static MessageReceiverPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, MessageReceiverPrx.class, MessageReceiverPrxHelper.class);
    }

    public static MessageReceiverPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, MessageReceiverPrx.class, MessageReceiverPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Chat::MessageReceiver",
        "::Ice::Object"
    };

    public static String ice_staticId()
    {
        return __ids[0];
    }

    public static void __write(IceInternal.BasicStream __os, MessageReceiverPrx v)
    {
        __os.writeProxy(v);
    }

    public static MessageReceiverPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MessageReceiverPrxHelper result = new MessageReceiverPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
