// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface Room extends Ice.Object,
                              _RoomOperations, _RoomOperationsNC
{
    public static final String ice_staticId = "::Chat::Room";

    public static final long serialVersionUID = 874146908L;
}
