// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface RoomPrx extends Ice.ObjectPrx
{
    public boolean login(String user, MessageReceiverPrx receiver);

    public boolean login(String user, MessageReceiverPrx receiver, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(String user, MessageReceiverPrx receiver);

    public Ice.AsyncResult begin_login(String user, MessageReceiverPrx receiver, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(String user, MessageReceiverPrx receiver, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(String user, MessageReceiverPrx receiver, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(String user, MessageReceiverPrx receiver, Callback_Room_login __cb);

    public Ice.AsyncResult begin_login(String user, MessageReceiverPrx receiver, java.util.Map<String, String> __ctx, Callback_Room_login __cb);

    public Ice.AsyncResult begin_login(String user, 
                                       MessageReceiverPrx receiver, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(String user, 
                                       MessageReceiverPrx receiver, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_login(String user, 
                                       MessageReceiverPrx receiver, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(String user, 
                                       MessageReceiverPrx receiver, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_login(Ice.AsyncResult __result);

    public void logout(String user);

    public void logout(String user, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout(String user);

    public Ice.AsyncResult begin_logout(String user, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout(String user, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(String user, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(String user, Callback_Room_logout __cb);

    public Ice.AsyncResult begin_logout(String user, java.util.Map<String, String> __ctx, Callback_Room_logout __cb);

    public Ice.AsyncResult begin_logout(String user, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logout(String user, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_logout(String user, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logout(String user, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_logout(Ice.AsyncResult __result);

    public void sendMessage(String user, String message);

    public void sendMessage(String user, String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMessage(String user, String message);

    public Ice.AsyncResult begin_sendMessage(String user, String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMessage(String user, String message, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMessage(String user, String message, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMessage(String user, String message, Callback_Room_sendMessage __cb);

    public Ice.AsyncResult begin_sendMessage(String user, String message, java.util.Map<String, String> __ctx, Callback_Room_sendMessage __cb);

    public Ice.AsyncResult begin_sendMessage(String user, 
                                             String message, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendMessage(String user, 
                                             String message, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendMessage(String user, 
                                             String message, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendMessage(String user, 
                                             String message, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendMessage(Ice.AsyncResult __result);
}
