// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface RoomPrx extends Ice.ObjectPrx
{
    public boolean login(String user, CMDReceiverPrx receiver);

    public boolean login(String user, CMDReceiverPrx receiver, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(String user, CMDReceiverPrx receiver);

    public Ice.AsyncResult begin_login(String user, CMDReceiverPrx receiver, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(String user, CMDReceiverPrx receiver, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(String user, CMDReceiverPrx receiver, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(String user, CMDReceiverPrx receiver, Callback_Room_login __cb);

    public Ice.AsyncResult begin_login(String user, CMDReceiverPrx receiver, java.util.Map<String, String> __ctx, Callback_Room_login __cb);

    public Ice.AsyncResult begin_login(String user, 
                                       CMDReceiverPrx receiver, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(String user, 
                                       CMDReceiverPrx receiver, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_login(String user, 
                                       CMDReceiverPrx receiver, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(String user, 
                                       CMDReceiverPrx receiver, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_login(Ice.AsyncResult __result);

    public void logout(String user);

    public void logout(String user, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout(String user);

    public Ice.AsyncResult begin_logout(String user, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout(String user, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(String user, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(String user, Callback_Room_logout __cb);

    public Ice.AsyncResult begin_logout(String user, java.util.Map<String, String> __ctx, Callback_Room_logout __cb);

    public Ice.AsyncResult begin_logout(String user, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logout(String user, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_logout(String user, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logout(String user, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_logout(Ice.AsyncResult __result);

    public void sendCMD(String user, String CMD);

    public void sendCMD(String user, String CMD, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendCMD(String user, String CMD);

    public Ice.AsyncResult begin_sendCMD(String user, String CMD, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendCMD(String user, String CMD, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendCMD(String user, String CMD, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendCMD(String user, String CMD, Callback_Room_sendCMD __cb);

    public Ice.AsyncResult begin_sendCMD(String user, String CMD, java.util.Map<String, String> __ctx, Callback_Room_sendCMD __cb);

    public Ice.AsyncResult begin_sendCMD(String user, 
                                         String CMD, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendCMD(String user, 
                                         String CMD, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendCMD(String user, 
                                         String CMD, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendCMD(String user, 
                                         String CMD, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendCMD(Ice.AsyncResult __result);
}
